import {
	boolean,
	integer,
	pgTable,
	serial,
	text,
	timestamp,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
	id: serial("id").primaryKey(),
	discordId: text("discord_id").notNull(),
	guildId: text("guild_id").notNull(),
	bot: text("bot").default("false"),
	username: text("username").notNull(),
	displayName: text("display_name").notNull(),
	nickname: text("nickname"),
	discriminator: text("discriminator").notNull(),
	avatar: text("avatar"),
	status: text("status"),
	roles: text("roles").array(),
	joinedAt: timestamp("joined_at").notNull(),
	lastSeen: timestamp("last_seen").notNull(),
	avatarHistory: text("avatar_history"),
	usernameHistory: text("username_history").array(),
	displayNameHistory: text("display_name_history").array(),
	statusHistory: text("status_history"),
	emoji: text("emoji"),
	title: text("title"),
	summary: text("summary"),
	keywords: text("keywords").array(),
	notes: text("notes").array(),
	relationships: text("relationships"),
	modPreferences: text("mod_preferences"),
	voiceInteractions: text("voice_interactions"),
	createdAt: timestamp("created_at").defaultNow(),
	updatedAt: timestamp("updated_at").defaultNow(),
});

export const channels = pgTable("channels", {
	id: serial("id").primaryKey(),
	discordId: text("discord_id").notNull(),
	guildId: text("guild_id").notNull(),
	channelName: text("channel_name").notNull(),
	position: integer("position").notNull(),
	status: text("status"),
	isActive: boolean("is_active"),
	activeUserIds: text("active_user_ids").array(),
	memberCount: integer("member_count"),
	createdAt: timestamp("created_at").defaultNow(),
	updatedAt: timestamp("updated_at").defaultNow(),
});
