CREATE TABLE "channels" (
	"id" serial PRIMARY KEY NOT NULL,
	"discord_id" text NOT NULL,
	"guild_id" text NOT NULL,
	"channel_name" text NOT NULL,
	"position" integer NOT NULL,
	"status" text,
	"is_active" boolean,
	"active_user_ids" text[],
	"member_count" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"discord_id" text NOT NULL,
	"guild_id" text NOT NULL,
	"bot" text DEFAULT 'false',
	"username" text NOT NULL,
	"display_name" text NOT NULL,
	"nickname" text,
	"discriminator" text NOT NULL,
	"avatar" text,
	"status" text,
	"roles" text[],
	"joined_at" timestamp NOT NULL,
	"last_seen" timestamp NOT NULL,
	"avatar_history" text,
	"username_history" text[],
	"display_name_history" text[],
	"status_history" text,
	"emoji" text,
	"title" text,
	"summary" text,
	"keywords" text[],
	"notes" text[],
	"relationships" text,
	"mod_preferences" text,
	"voice_interactions" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
